#!/usr/bin/bash

hyprctl activewindow -j | gojq -c -M

if [ "$1" == "--once" ]; then
  exit 0
else
  # socket=$(ls $XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock 2>/dev/null | head -n 1)
  # if [ -n "$socket" ]; then
  #   socat -u UNIX-CONNECT:"$socket" - | rg --line-buffered "window>>" | while read -r line; do
  #     hyprctl activewindow -j | gojq -c -M
  #   done
  # # if [ -n "$socket" ]; then
  # else
  #   hyprctl dispatchers | rg --line-buffered "window>>" | while read -r line; do
  #     hyprctl activewindow -j | gojq -c -M
  #   done
  # fi
  socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | rg --line-buffered "window>>" | while read -r line; do
    hyprctl activewindow -j | gojq -c -M
  done
fi

