#!/usr/bin/bash

focusedws=$(hyprctl activewindow -j | gojq -c -M '.workspace.id')
echo $focusedws

if [[ "$focusedws" == 'null' ]]; then
  echo 1
fi

if [ "$1" == "--once" ]; then
  exit 0
else
  socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | rg --line-buffered "workspace>>" | while read -r line; do
    case ${line%>>*} in
      "workspace")
        focusedws=${line#*>>}
        echo $focusedws
        ;;
    esac  
  done
fi

# #!/usr/bin/bash
# cd ~/.config/eww

# get_active_ws() {
#   focusedws=$(hyprctl activewindow -j | gojq -r '.workspace.id // 1')
#   echo "$focusedws"
# }

# # Run once
# get_active_ws

# if [ "$1" == "--once" ]; then
#   exit 0
# else
#   socket=$(ls $XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock2>/dev/null | head -n 1)
#   if [ -n "$socket" ]; then
#     socat -u UNIX-CONNECT:"$socket" - | rg --line-buffered "workspace>>" | while read -r line; do
#       case ${line%>>*} in
#         "workspace")
#           focusedws=${line#*>>}
#           echo "$focusedws"
#           ;;
#       esac  
#     done
#   # if [ -n "$socket" ]; then
#   else
#     hyprctl dispatchers | rg --line-buffered "workspace>>" | while read -r line; do
#       case ${line%>>*} in
#         "workspace")
#           focusedws=${line#*>>}
#           echo "$focusedws"
#           ;;
#       esac  
#     done
#   fi
# fi
