#!/usr/bin/bash

geticons -t $(gsettings get org.gnome.desktop.interface icon-theme | sed "s/'//g") "firefox" | head -n 1
socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
  echo "$line"
done

# # find the Hyprland socket
# socket=$(ls -1d $XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock 2>/dev/null | head -n1)

# if [ -n "$socket" ]; then
#   # listen to socket events
#   socat -u UNIX-CONNECT:"$socket" - \
#     | rg --line-buffered "window>>" \
#     | while read -r line; do
#         echo "$line"
#       done
# else
#   # fallback to hyprctl dispatchers
#   hyprctl dispatchers \
#     | rg --line-buffered "window>>" \
#     | while read -r line; do
#         echo "$line"
#       done
# fi


