#!/usr/bin/bash

scripts/overview --row 1

if [ "$1" == "--once" ]; then
  exit 0
else
  # # find the Hyprland socket
  # socket=$(ls -1d $XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock 2>/dev/null | head -n1)

  # if [ -n "$socket" ]; then
  #   # listen to socket events
  #   socat -u UNIX-CONNECT:"$socket" - \
  #     | rg --line-buffered "window>>" \
  #     | while read -r line; do
  #         sleep 0.025
  #         scripts/overview --row 1
  #       done
  # else
  #   # fallback to hyprctl dispatchers
  #   hyprctl dispatchers \
  #     | rg --line-buffered "window>>" \
  #     | while read -r line; do
  #         sleep 0.025
  #         scripts/overview 0.025
  #       done
  # fi
  socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | rg --line-buffered "window>>" | while read -r line; do
    # This sleep is necessary
    # It prevents the script from being faster than hyprctl
    sleep 0.025
    scripts/overview --row 1
  done
  # I'm sorry, i need to change, i think my computer is the problem
fi